// @generated
// This file is @generated by prost-build.
/// TaskMessage is the internal representation of a task with additional
/// metadata fields.
/// Next ID: 16
/// Source: <https://github.com/hibiken/asynq/blob/v0.26.0/internal/proto/asynq.proto#L12-L71>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskMessage {
    /// Type indicates the kind of the task to be performed.
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    /// Payload holds data needed to process the task.
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Headers holds additional metadata for the task.
    #[prost(map = "string, string", tag = "15")]
    pub headers:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Unique identifier for the task.
    #[prost(string, tag = "3")]
    pub id: ::prost::alloc::string::String,
    /// Name of the queue to which this task belongs.
    #[prost(string, tag = "4")]
    pub queue: ::prost::alloc::string::String,
    /// Max number of retries for this task.
    #[prost(int32, tag = "5")]
    pub retry: i32,
    /// Number of times this task has been retried so far.
    #[prost(int32, tag = "6")]
    pub retried: i32,
    /// Error message from the last failure.
    #[prost(string, tag = "7")]
    pub error_msg: ::prost::alloc::string::String,
    /// Time of last failure in Unix time,
    /// the number of seconds elapsed since January 1, 1970 UTC.
    /// Use zero to indicate no last failure.
    #[prost(int64, tag = "11")]
    pub last_failed_at: i64,
    /// Timeout specifies timeout in seconds.
    /// Use zero to indicate no timeout.
    #[prost(int64, tag = "8")]
    pub timeout: i64,
    /// Deadline specifies the deadline for the task in Unix time,
    /// the number of seconds elapsed since January 1, 1970 UTC.
    /// Use zero to indicate no deadline.
    #[prost(int64, tag = "9")]
    pub deadline: i64,
    /// UniqueKey holds the redis key used for uniqueness lock for this task.
    /// Empty string indicates that no uniqueness lock was used.
    #[prost(string, tag = "10")]
    pub unique_key: ::prost::alloc::string::String,
    /// GroupKey is a name of the group used for task aggregation.
    /// This field is optional and empty value means no aggregation for the task.
    #[prost(string, tag = "14")]
    pub group_key: ::prost::alloc::string::String,
    /// Retention period specified in a number of seconds.
    /// The task will be stored in redis as a completed task until the TTL
    /// expires.
    #[prost(int64, tag = "12")]
    pub retention: i64,
    /// Time when the task completed in success in Unix time,
    /// the number of seconds elapsed since January 1, 1970 UTC.
    /// This field is populated if result_ttl > 0 upon completion.
    #[prost(int64, tag = "13")]
    pub completed_at: i64,
}
/// Source: <https://github.com/hibiken/asynq/blob/v0.26.0/internal/proto/asynq.proto#L97-L113>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerInfo {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub pid: i32,
    #[prost(string, tag = "3")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub concurrency: i32,
    #[prost(map = "string, int32", tag = "5")]
    pub queues: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(bool, tag = "6")]
    pub strict_priority: bool,
    #[prost(string, tag = "7")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag = "9")]
    pub active_worker_count: i32,
}
/// Source: <https://github.com/hibiken/asynq/blob/v0.26.0/internal/proto/asynq.proto#L115-L137>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerInfo {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub pid: i32,
    #[prost(string, tag = "3")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub task_type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub task_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "7")]
    pub queue: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub deadline: ::core::option::Option<::prost_types::Timestamp>,
}
/// Source: <https://github.com/hibiken/asynq/blob/v0.26.0/internal/proto/asynq.proto#L139-L147>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchedulerEntry {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub spec: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub task_type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub task_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag = "5")]
    pub enqueue_options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub next_enqueue_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub prev_enqueue_time: ::core::option::Option<::prost_types::Timestamp>,
}
/// Source: <https://github.com/hibiken/asynq/blob/v0.26.0/internal/proto/asynq.proto#L163-L171>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchedulerEnqueueEvent {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub enqueue_time: ::core::option::Option<::prost_types::Timestamp>,
}
// @@protoc_insertion_point(module)
