use crate::broker::redis::RedisScript;

impl RedisScript {
    /// Reference: Asynq v0.26.0 keeps Redis Lua commands as a fixed script
    /// set under `internal/rdb`.
    /// <https://github.com/hibiken/asynq/blob/v0.26.0/internal/rdb/rdb.go#L82-L735>.
    pub const ALL: [Self; 48] = [
        Self::Enqueue,
        Self::EnqueueUnique,
        Self::Schedule,
        Self::ScheduleUnique,
        Self::AddToGroup,
        Self::AddToGroupUnique,
        Self::Dequeue,
        Self::Done,
        Self::DoneUnique,
        Self::MarkAsComplete,
        Self::MarkAsCompleteUnique,
        Self::Retry,
        Self::Archive,
        Self::Requeue,
        Self::Forward,
        Self::DeleteExpiredCompletedTasks,
        Self::AggregationCheck,
        Self::ReadAggregationSet,
        Self::DeleteAggregationSet,
        Self::ReclaimStaleAggregationSets,
        Self::WriteServerState,
        Self::ClearServerState,
        Self::ListServerKeys,
        Self::ListWorkerKeys,
        Self::WriteSchedulerEntries,
        Self::ListSchedulerEntries,
        Self::RecordSchedulerEnqueueEvent,
        Self::DeleteQueue,
        Self::DeleteQueueForce,
        Self::DeleteTask,
        Self::RunTask,
        Self::ArchiveTask,
        Self::UpdateTaskPayload,
        Self::CurrentQueueStats,
        Self::QueueMemoryUsage,
        Self::HistoricalQueueStats,
        Self::GroupStats,
        Self::TaskInfo,
        Self::ListTasks,
        Self::RunAllTasks,
        Self::ArchiveAllTasks,
        Self::ArchiveAllPendingTasks,
        Self::DeleteAllTasks,
        Self::DeleteAllPendingTasks,
        Self::RunAllAggregatingTasks,
        Self::ArchiveAllAggregatingTasks,
        Self::DeleteAllAggregatingTasks,
        Self::ListLeaseExpired,
    ];
}
